eureka-server: http://192.168.1.35:7777
spring-datasource-username: root
spring-datasource-password: sfydev123
spring-datasource-url: jdbc:mysql://192.168.1.33:3306/sfy-shop?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring-redis-database: 5 #Redis数据库索引（默认为0）
spring-redis-host: 192.168.1.33 #Redis服务器地址
spring-redis-port: 6379 #Redis服务器连接端口
spring-redis-password: sfydev123 #Redis服务器连接密码（默认为空）
spring-redis-timeout: 10000 #连接超时时间（毫秒）
hystrix-timeoutInMilliseconds: 3000
security-server: http://192.168.1.36:5010
security-name: admin
security-password: sfy@123@active
suagger-package: com.sfy.mall.controller
suagger-title: 电商接口
suagger-description: 电商接口文档说明
suagger-version: all
feign-url: http://192.168.1.23:18899
rabbitmq-host: 192.168.1.33
rabbitmq-port: 5672
rabbitmq-username: admin
rabbitmq-password: sfydev123
rabbitmq-virtualHost: sfy
client-id: clientId
client-secret: 3628e656eb34661af0e8eee788618593
type-aliases-package: com.sfy.mall.entity
mapper-locations: classpath:/mapper/*.xml



eureka:
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: ${security-name}
      user.password: ${security-password}

spring:
  datasource:
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
    driver-class-name: com.mysql.jdbc.Driver
    url: ${spring-datasource-url}
  redis:
    database: ${spring-redis-database}
    host: ${spring-redis-host}
    port: ${spring-redis-port}
    password: ${spring-redis-password}
    timeout: ${spring-redis-timeout}
  rabbitmq: #RabbitMQ相关的配置
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
    virtualHost: ${rabbitmq-virtualHost}
  jackson:
    #date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: true  # 时间类型，返回时间戳

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000

server:
  port: 5006

security:
  oauth2:
    resource:
      filter-order: 3
      token-info-uri: ${security-server}/oauth/check_token
    client:
      client-id: ${client-id}
      client-secret: ${client-secret}
      user-authorization-uri: ${security-server}/oauth/authorize
      access-token-uri: ${security-server}/oauth/token
  user:
    name: ${security-name}
    password: ${security-password}

Myconfig: #自定义的属性和值
  Package: ${suagger-package}
  title: ${suagger-title}
  description: ${suagger-description}
  version: ${suagger-version}
  redisPort: ${spring-redis-port}
  redisIp: ${spring-redis-host}
  redisPassword: ${spring-redis-password}

pay:
  url: http://192.168.0.165/pay
  merchantId: 1001
  merchantKey: test1001
  channelNo: 95
  callBackUrl: http://192.168.0.161:20877/pay/callBack
  description: sfy

sfy:
  corn_auto_pending_cancel: 0 0-59/1 * * * ?
  corn_auto_stock_reset: 0 0-59/5 * * * ?
  corn_auto_shopCart_clear: 59 59 23 * * ?
  order:
    timeout:
      cancel: 60 #60分钟
  shopCart:
    clear: 30 #30天



info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"


mybatis:
  mapperLocations: ${mapper-locations}
  typeAliasesPackage: ${type-aliases-package}