eureka-server: http://127.0.0.1:7777
spring-datasource-username: root
spring-datasource-password: sfydev123
spring-datasource-url: jdbc:mysql://192.168.1.33:3306/sfy-user-v2?useUnicode=true&characterEncoding=utf-8&useSSL=false
spring-redis-database: 5 #Redis数据库索引（默认为0）
spring-redis-host: 192.168.1.33 #Redis服务器地址
spring-redis-port: 6379 #Redis服务器连接端口
spring-redis-password: sfydev123 #Redis服务器连接密码（默认为空）
spring-redis-timeout: 10000 #连接超时时间（毫秒）
hystrix-timeoutInMilliseconds: 3000
security-server: http://127.0.0.1:5010
security-name: admin
security-password: sfy@123@active
suagger-package: com.sfy.user.controller
suagger-title: 用户中心接口
suagger-description: 用户中心接口接口文档说明
suagger-version: all
feign-url: http://192.168.1.23:18899
rabbitmq-host: 192.168.1.33
rabbitmq-port: 5672
rabbitmq-username: admin
rabbitmq-password: sfydev123
rabbitmq-virtualHost: sfy
client-id: clientId
#client-secret: $2a$10$IslEnLgNDrwfxdqzCUnx5eY.cF9iY8COCuIXK3TBmQD8Ab1H9mR66
client-secret: 3628e656eb34661af0e8eee788618593
type-aliases-package: com.sfy.**.entity
mapper-locations: classpath*:/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: ${eureka-server}/eureka/
  instance:
    preferIpAddress: true
    hostname: ${spring.cloud.client.ipAddress}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
    metadata-map:
      user.name: ${security-name}
      user.password: ${security-password}

spring:
  datasource:
    username: ${spring-datasource-username}
    password: ${spring-datasource-password}
    driver-class-name: com.mysql.jdbc.Driver
    url: ${spring-datasource-url}
  redis:
    database: ${spring-redis-database}
    host: ${spring-redis-host}
    port: ${spring-redis-port}
    password: ${spring-redis-password}
    timeout: ${spring-redis-timeout}
  rabbitmq: #RabbitMQ相关的配置
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
    virtualHost: ${rabbitmq-virtualHost}

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: ${hystrix-timeoutInMilliseconds}

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

security:
  oauth2:
    resource:
      filter-order: 3
      token-info-uri: ${security-server}/oauth/check_token
    client:
      client-id: ${client-id}
      client-secret: ${client-secret}
      user-authorization-uri: ${security-server}/oauth/authorize
      access-token-uri: ${security-server}/oauth/token
  user:
    name: ${security-name}
    password: ${security-password}


Myconfig: #自定义的属性和值
  Package: ${suagger-package}
  title: ${suagger-title}
  description: ${suagger-description}
  version: ${suagger-version}
  redisPort: ${spring-redis-port}
  redisIp: ${spring-redis-host}
  redisPassword: ${spring-redis-password}

sms:
  jiguang:
    appKey: 98c89d750bd1cb10d4b45f6d
    masterSecret: 7e5bb0a03b71c663fffe425e
    oldCodeTempId: 158489
    codeTempId: 164032
    commonTempId:  #

mybatis-plus:
  mapper-locations: ${mapper-locations}
  type-aliases-package: ${type-aliases-package}

#management:
#  security:
#    enabled: false
#    role: ROLE_ACTUATOR
