spring:
  application:
    name: sfy-config-server
  profiles:
    active: git

server:
  port: 6688

#本地配置
#spring:
#  cloud:
#    config:
#      server:
#        native:
##          search-locations: classpath:properties/dev/
#          search-locations: /opt/properties/dev/
#  application:
#    name: microservice-config-server
#  profiles:
#    active: native  # 配置使用本地储存
#  rabbitmq: #RabbitMQ相关的配置
#    host: 192.168.1.33
#    port: 5672
#    username: admin
#    password: sfydev123
#    virtualHost: sfy
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://192.168.1.33:7777/eureka/
#  instance:
#    preferIpAddress: true
#    hostname: ${spring.cloud.client.ipAddress}
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#
#management:
#  security:
#    enabled: false #是否开启actuator安全认证
#
#info:
#  app:
#    name: "@project.name@"
#    description: "@project.description@"
#    version: "@project.version@"